Let's start with a brief introduction to Pandas before creating some graphs with Plotly. We'll explore a simple data set from the state of Delaware's Open Data portal. Specifically, we'll be using the [Aerial Waterfowl Survey Data](https://data.delaware.gov/Energy-and-Environment/Aerial-Waterfowl-Survey-Data/bxyv-7mgn). 

Tips for those new to Python:
* lines starting with '#' are comments
* Run the cells in order!

If you want more information about Jupyter, checkout this [Quick Start Guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/)

In [1]:
# Run this if you need to install the requirements (Prefixing with ! runs it as a shell command).
# You do not need to run this in Azure, so it is commented out. But you should run it if you have
# Jupyter running on your own computer.
#!pip install -r requirements.txt

In [1]:
# Import the libraries we're using
import pandas as pd

In [2]:
# Load the waterfowl data into a dataframe
url = "https://data.delaware.gov/api/views/bxyv-7mgn/rows.csv?accessType=DOWNLOAD"
waterfowl_df = pd.read_csv(url)

In [3]:
# Time to explore the data.

# First, check the number of rows and columns against the data on the portal!
waterfowl_df.shape

(1942, 36)

In [4]:
# As of February 10, 2018, we have 1942 rows and 36 columns. If you do this later, you may have more than 1942 rows.
# Check your output against the open data portal!

# Now look at the column types
waterfowl_df.dtypes

Year                             int64
Month                           object
Time Period                     object
Unit                           float64
Atlantic Brant                   int64
Canada Goose                     int64
Snow Goose                       int64
Greater White-fronted Goose      int64
American Black Duck              int64
Mallard                          int64
Northern Pintail                 int64
American Green-winged Teal       int64
Blue-winged Teal                 int64
Gadwall                          int64
American Wigeon                  int64
Northern Shoveler                int64
Wood Duck                        int64
Canvasback                       int64
Redhead                          int64
Scaup                            int64
Ring-necked Duck                 int64
Common Merganser                 int64
Red-breasted Merganser           int64
Hooded Merganser                 int64
Mergansers                     float64
Ruddy Duck                       int64
White-winged Scoter              int64
Surf Scoter                      int64
Black Scoter                     int64
Scoters                          int64
Bufflehead                       int64
Common Goldeneye                 int64
Long-tailed Duck                 int64
Mute Swan                        int64
Tundra Swan                      int64
American Coot                    int64
dtype: object

In [5]:
# Weird that Mergansers is a float. That's something you would explore if you wanted to chart that bird.

# Look at the first few rows of data. Compare to the data on the data portal!
waterfowl_df.head()

,Year,Month,Time Period,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
0,1974,October,NaN,1.0,0,125,0,0,446,42,...,0,0,0,0,5,0,0,0,0,0
1,1974,October,NaN,2.0,0,75,0,0,119,1250,...,0,0,0,0,0,0,0,0,0,0
2,1974,October,NaN,3.0,0,12471,0,0,1512,5046,...,0,0,0,0,0,0,0,0,0,0
3,1974,October,NaN,4.0,0,4709,0,0,512,1502,...,0,0,0,0,5,0,0,0,0,0
4,1974,October,NaN,5.0,0,25762,1801,0,2708,1190,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# Look at the last few rows:



waterfowl_df.tail()

,Year,Month,Time Period,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
1937,2018,January,MWS,10.0,700,2251,13504,0,672,556,...,0,0,0,0,9202,38,8,0,72,0
1938,2018,January,MWS,11.0,0,1475,0,0,537,30,...,0,0,0,0,429,0,0,2,2110,0
1939,2018,January,Late,5.0,0,5636,5729,0,768,2759,...,0,0,0,0,31,0,0,0,350,0
1940,2018,January,Late,6.0,0,2992,507,0,1527,2539,...,0,520,20,0,0,0,0,2,150,0
1941,2018,January,Late,7.0,0,4402,10097,0,2681,1048,...,0,18447,4842,0,67,24,0,0,238,0

## Note

Looking at the head and tail, you can see that far left is an unnamed column that starts at 0 and ends at 1941 (as of Feb. 10, 2018!). That is the index, and it lets you access a single row very quickly.

Many programming languages start counting at 0 rather than 1. But if you were to do this in the R programming language, it would start with 1. Likewise, if you import this into a database the first row would also be 1. But this is Python, and Python starts at 0.

In [7]:
# Pandas has a handy describe() function
# count tells the number of values that column has (some columns can be NaN (Not a Number))
# Look at the mean, median (50%) and max
waterfowl_df.describe()

,Year,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,Northern Pintail,American Green-winged Teal,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
count,1942.000000,1939.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,...,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000,1942.000000
mean,1994.968074,5.997937,89.806385,4744.970649,7872.271885,0.002060,907.803296,839.964470,769.467044,1327.316684,...,0.001545,10.333162,2.627188,16.576210,56.825438,3.571061,0.494336,2.105561,28.502575,22.121009
std,12.539726,3.061124,385.969251,7281.493648,18697.045602,0.045349,1261.281078,1686.625506,2746.101723,4522.401068,...,0.068076,418.971320,109.917645,229.163767,276.037926,25.405376,9.171485,9.162772,164.924808,155.091136
min,1974.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1984.000000,3.000000,0.000000,550.000000,0.000000,0.000000,112.250000,62.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1995.000000,6.000000,0.000000,2254.000000,0.000000,0.000000,424.000000,270.000000,3.000000,10.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2006.000000,9.000000,0.000000,5933.000000,5952.500000,0.000000,1298.000000,858.000000,336.000000,539.250000,...,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,2.000000,0.000000
max,2018.000000,11.000000,5721.000000,70432.000000,198730.000000,1.000000,16134.000000,19981.000000,35768.000000,65727.000000,...,3.000000,18447.000000,4842.000000,8500.000000,9202.000000,611.000000,350.000000,152.000000,3450.000000,2684.000000

In [8]:
# Let's sum all the columns to select what birds we want
waterfowl_df.sum()

Year                                                                     3874228
Month                          OctoberOctoberOctoberOctoberOctoberOctoberOcto...
Unit                                                                       11630
Atlantic Brant                                                            174404
Canada Goose                                                             9214733
Snow Goose                                                              15287952
Greater White-fronted Goose                                                    4
American Black Duck                                                      1762954
Mallard                                                                  1631211
Northern Pintail                                                         1494305
American Green-winged Teal                                               2577649
Blue-winged Teal                                                           15209
Gadwall                                                                   300318
American Wigeon                                                           168794
Northern Shoveler                                                         202781
Wood Duck                                                                  14863
Canvasback                                                                 82557
Redhead                                                                      125
Scaup                                                                     330370
Ring-necked Duck                                                           66674
Common Merganser                                                            5728
Red-breasted Merganser                                                       527
Hooded Merganser                                                            4851
Mergansers                                                                 27702
Ruddy Duck                                                                152945
White-winged Scoter                                                            3
Surf Scoter                                                                20067
Black Scoter                                                                5102
Scoters                                                                    32191
Bufflehead                                                                110355
Common Goldeneye                                                            6935
Long-tailed Duck                                                             960
Mute Swan                                                                   4089
Tundra Swan                                                                55352
American Coot                                                              42959
dtype: object

In [9]:
# Let's look at the number of rows for each year
waterfowl_df.groupby('Year').count()

,Month,Time Period,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,Northern Pintail,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
Year,,,,,,,,,,,,,,,,,,,,,
1974,33,0,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
1975,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1976,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1977,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1978,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1979,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1980,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1981,54,0,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,54,54,54
1982,65,0,65,65,65,65,65,65,65,65,...,65,65,65,65,65,65,65,65,65,65
1983,53,0,53,53,53,53,53,53,53,53,...,53,53,53,53,53,53,53,53,53,53
1984,54,0,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,54,54,54
1985,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1986,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1987,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1988,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1989,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1990,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1991,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1992,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1993,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1994,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1995,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1996,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1997,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
1998,50,0,50,50,50,50,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
1999,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2000,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2001,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2002,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2003,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2004,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2005,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2006,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2007,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2008,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2009,44,0,44,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2010,34,12,34,34,34,34,34,34,34,34,...,34,34,34,34,34,34,34,34,34,34
2011,37,37,34,37,37,37,37,37,37,37,...,37,37,37,37,37,37,37,37,37,37
2012,37,37,37,37,37,37,37,37,37,37,...,37,37,37,37,37,37,37,37,37,37
2013,40,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
2014,40,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
2015,40,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
2016,31,31,31,31,31,31,31,31,31,31,...,31,31,31,31,31,31,31,31,31,31
2017,40,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
2018,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14

In [12]:
# ***** This cell requires you to fill something in! *****

# Copy the previous command, and paste it below.
# Before running, edit it to get the sum by year.
# This is an example of "method chaining," and it's part of the power of Pandas!

waterfowl_df.groupby('Year').sum()

,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,Northern Pintail,American Green-winged Teal,Blue-winged Teal,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
Year,,,,,,,,,,,,,,,,,,,,,
1974,198.0,853,175190,8180,0,22847,23110,15673,25918,35,...,0,0,0,246,327,20,0,48,174,0
1975,264.0,2375,229957,18419,0,27756,14873,6748,15873,75,...,0,0,0,758,1130,73,0,49,4493,0
1976,264.0,10955,392543,15866,0,59845,63252,20666,16526,0,...,0,0,0,253,1533,1059,0,41,1020,0
1977,264.0,13419,405201,11031,0,59838,52941,12280,22054,265,...,0,0,0,286,1121,84,4,35,3309,0
1978,264.0,2715,365457,22410,0,67515,65535,17213,38744,501,...,0,0,0,1795,1695,280,1,50,2244,0
1979,264.0,11155,306433,19221,0,49839,38989,11118,21494,61,...,0,0,0,137,1923,307,17,10,2977,0
1980,264.0,7205,342276,17896,0,43982,34309,13745,12855,0,...,0,0,0,230,3477,74,15,8,1778,0
1981,320.0,10372,291346,21231,0,51298,37610,16146,26867,1282,...,0,0,0,273,922,301,30,0,980,0
1982,395.0,10407,398081,30466,0,43367,25266,10066,18719,1191,...,0,0,0,1661,1573,602,11,0,321,0
1983,320.0,1360,233643,63629,0,48150,29849,12427,27383,1174,...,0,0,0,132,616,373,11,24,3332,0
1984,320.0,4409,279458,191563,0,49337,42876,6247,29907,1180,...,0,0,0,488,2407,515,0,72,1008,0
1985,264.0,5006,246892,122910,0,44781,30703,10766,31411,60,...,0,0,0,3752,2003,394,6,77,582,0
1986,264.0,363,283365,109026,0,32169,31867,8640,35872,109,...,0,0,0,150,483,48,29,84,795,0
1987,264.0,525,190391,83356,0,35465,25764,7765,24781,4,...,0,0,0,371,1418,137,0,4,1771,0
1988,264.0,2340,217448,168560,0,41096,32160,9772,23717,250,...,0,0,0,1114,2225,115,50,0,341,0
1989,264.0,2386,150999,202812,0,37545,23406,29021,49918,0,...,0,0,0,2086,1180,35,0,25,495,0
1990,264.0,2140,159874,306829,0,42842,38411,27785,94567,120,...,0,0,0,266,3396,446,0,10,605,0
1991,264.0,2395,174011,281683,0,45388,34784,46190,127780,0,...,0,0,0,805,2167,65,0,16,226,0
1992,264.0,1470,160196,404009,0,53829,33173,34976,79456,0,...,0,0,0,85,1827,126,0,28,217,0
1993,264.0,1492,151515,484599,0,50843,33367,65235,101409,0,...,0,0,0,0,2563,35,0,116,190,0
1994,264.0,3470,174773,792037,0,46332,35191,66165,144907,80,...,0,0,0,40,1240,6,0,85,192,0
1995,264.0,3761,178633,399275,0,39777,27128,57118,89193,10,...,0,0,0,4965,3222,2,0,31,580,0
1996,264.0,5675,122849,575852,0,44585,44089,81348,123255,0,...,0,0,0,11080,3070,0,0,29,568,0
1997,264.0,4580,165837,929027,0,35658,31859,79181,109655,0,...,0,0,0,0,2764,313,0,97,1424,0
1998,297.0,2856,180020,815150,0,36156,30341,66241,130553,5162,...,0,0,0,0,2651,49,0,90,1950,0
1999,264.0,4190,210983,750026,0,35063,24128,36135,149920,5,...,0,0,0,623,2726,611,0,163,459,0
2000,264.0,9471,206915,707191,0,31440,25041,48971,150081,0,...,0,0,0,180,2803,0,0,194,1721,0
2001,264.0,8198,282361,690471,0,28952,26061,41330,54760,256,...,0,0,0,32,2858,0,0,230,367,0
2002,264.0,7484,232053,593757,0,35870,34996,71048,74694,0,...,0,0,0,0,2779,29,2,187,1250,0
2003,264.0,4716,256793,783683,0,28767,34806,102016,113019,0,...,0,0,0,52,3189,10,0,273,1073,0
2004,264.0,4343,234501,434990,0,27554,40099,54358,77595,22,...,0,0,0,10,3324,0,0,279,902,0
2005,264.0,4063,177499,303493,0,23407,32921,75082,82984,0,...,0,0,0,0,3220,0,0,366,549,0
2006,264.0,5006,210809,523997,0,23997,37215,84171,94266,0,...,0,0,0,72,2004,0,0,572,579,0
2007,264.0,3297,180907,348271,0,22630,29836,52851,79600,0,...,0,0,0,12,3471,0,0,338,654,0
2008,264.0,1850,172256,358323,0,24332,30754,24124,17121,150,...,0,0,0,25,2229,2,0,107,646,0
2009,264.0,972,167876,408964,0,27566,36487,50610,75199,200,...,0,0,0,12,2803,0,41,48,665,1440
2010,204.0,954,133644,340562,0,56485,70166,36358,36233,20,...,0,0,0,0,1344,90,6,19,542,775
2011,204.0,803,124134,542952,0,34312,41460,22106,30571,455,...,0,0,0,66,1664,44,1,90,1262,5923
2012,222.0,1307,102214,619951,0,37833,48717,14634,27050,74,...,0,0,0,0,1043,48,30,64,1185,5167
2013,240.0,961,88740,389930,1,43611,44708,11817,20614,650,...,0,0,2,30,1628,116,0,27,1923,10026
2014,240.0,600,97750,569907,1,48477,37961,11779,20051,931,...,0,0,0,0,4437,148,9,34,1139,8759
2015,240.0,100,98803,288683,0,45521,45942,13632,29066,337,...,3,1080,159,4,3489,27,20,6,1368,4151
2016,186.0,0,64447,263220,0,21943,34164,3097,3806,9,...,0,0,0,0,1471,10,0,17,1144,1079
2017,240.0,1355,125687,197038,1,39754,61716,7490,17836,541,...,0,20,79,100,4159,245,319,35,3059,4389
2018,84.0,1050,69973,77506,1,15200,13180,164,369,0,...,0,18967,4862,0,12781,96,358,11,3293,1250

In [14]:
# Going back to the .count() example, most years have 44 rows, but there are discrepencies!

# Let's look at the counts of January in each year
waterfowl_df_january = waterfowl_df[waterfowl_df['Month']=='January']
waterfowl_df_january.groupby('Year').count()

,Month,Time Period,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,Northern Pintail,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
Year,,,,,,,,,,,,,,,,,,,,,
1975,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1976,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1977,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1978,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1979,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1980,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1981,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1982,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1983,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1984,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1985,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1986,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1987,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1988,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1989,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1990,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1991,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1992,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1993,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1994,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1995,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1996,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1997,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1998,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1999,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2000,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2001,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2002,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2003,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2004,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2005,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2006,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2007,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2008,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2009,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2010,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2011,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
2012,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
2013,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
2014,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
2015,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
2016,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
2017,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
2018,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14

In [15]:
# In 2010 and before the number of observations in January was 11.
# Since 2011 it has 14. Let's look at 2010 and 2011 (ignore the warning if you see one)
waterfowl_df_january[waterfowl_df['Year'].isin([2010, 2011])]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

,Year,Month,Time Period,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
1629,2010,January,NaN,1.0,0,1027,0,0,73,240,...,0,0,0,0,0,0,0,3,0,0
1630,2010,January,NaN,2.0,0,5477,0,0,70,159,...,0,0,0,0,0,0,0,12,0,0
1631,2010,January,NaN,3.0,0,10592,3000,0,192,309,...,0,0,0,0,0,0,0,0,60,0
1632,2010,January,NaN,4.0,0,3933,3345,0,198,337,...,0,0,0,0,0,0,0,0,0,0
1633,2010,January,NaN,5.0,0,7770,24200,0,3011,3484,...,0,0,0,0,2,0,0,0,65,0
1634,2010,January,NaN,6.0,0,6255,10521,0,3337,2663,...,0,0,0,0,0,0,0,0,0,0
1635,2010,January,NaN,7.0,0,4551,2014,0,3139,1974,...,0,0,0,0,0,0,0,0,54,0
1636,2010,January,NaN,8.0,0,2917,11000,0,447,193,...,0,0,0,0,0,0,0,0,0,0
1637,2010,January,NaN,9.0,131,2810,0,0,307,121,...,0,0,0,0,400,6,0,0,36,0
1638,2010,January,NaN,10.0,373,1965,0,0,800,435,...,0,0,0,0,837,72,6,0,0,0
1639,2010,January,NaN,11.0,0,852,0,0,151,67,...,0,0,0,0,24,0,0,0,0,0
1663,2011,January,MWS,1.0,0,11799,0,0,0,210,...,0,0,0,0,0,0,0,0,0,0
1664,2011,January,MWS,2.0,0,6234,0,0,10,176,...,0,0,0,0,6,0,0,5,0,0
1665,2011,January,MWS,3.0,0,14735,0,0,97,102,...,0,0,0,0,0,0,0,0,0,0
1666,2011,January,MWS,4.0,0,3788,0,0,120,533,...,0,0,0,0,4,0,0,0,0,0
1667,2011,January,MWS,5.0,0,5782,13505,0,714,2994,...,0,0,0,0,0,0,0,0,213,0
1668,2011,January,MWS,6.0,0,3122,41200,0,1975,1546,...,0,0,0,0,0,0,0,0,15,0
1669,2011,January,MWS,7.0,0,3524,52451,0,1449,1074,...,0,0,0,0,8,0,0,0,30,0
1670,2011,January,MWS,8.0,0,772,25000,0,407,96,...,0,0,0,0,30,0,0,0,0,0
1671,2011,January,MWS,9.0,0,130,0,0,328,11,...,0,0,0,0,60,0,0,0,0,0
1672,2011,January,MWS,10.0,525,160,0,0,230,30,...,0,0,0,64,135,0,0,2,0,0
1673,2011,January,MWS,11.0,0,460,0,0,255,214,...,0,0,0,0,52,2,0,7,0,0
1674,2011,January,Late,5.0,0,2963,23000,0,2023,5460,...,0,0,0,0,0,0,0,0,10,0
1675,2011,January,Late,6.0,0,6237,101,0,1710,603,...,0,0,0,0,0,0,0,0,20,60
1676,2011,January,Late,7.0,0,4297,25635,0,2139,655,...,0,0,0,0,24,0,0,0,149,30

In [16]:
# ***** This cell requires you to fill something in! *****

# 2011 has three observations with the timeperiod set to 'Late'
# Remove observations where the timeperiod = 'Late' 
# (in otherwords, keep the observations where the time period does not equal (!=) 'Late') #REPLACE_ME
waterfowl_df_january_sub = waterfowl_df_january[waterfowl_df_january['Time Period']!='Late']

# Finish the previous line, then we'll check the counts again
waterfowl_df_january_sub.groupby('Year').count()

,Month,Time Period,Unit,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,Northern Pintail,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
Year,,,,,,,,,,,,,,,,,,,,,
1975,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1976,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1977,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1978,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1979,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1980,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1981,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1982,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1983,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1984,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1985,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1986,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1987,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1988,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1989,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1990,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1991,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1992,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1993,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1994,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1995,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1996,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1997,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1998,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
1999,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2000,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2001,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2002,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2003,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2004,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2005,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2006,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2007,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2008,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2009,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2010,11,0,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2011,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2012,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2013,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2014,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2015,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2016,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2017,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2018,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11

In [17]:
# We have 11 observations for each year! So far so good.
# Note: You'll see that 'Time Period' is 0 through 2010. That is because it is not set until 2010, and the
# .count() method only counts values that are set!

# In 2011 Delaware started counting some areas multiple times, but we only want to look at a single observation
# for each area ('Unit' in the data) for January of each year.

# Let's check unit counts
waterfowl_df_january_sub.groupby('Unit').count()

,Year,Month,Time Period,Atlantic Brant,Canada Goose,Snow Goose,Greater White-fronted Goose,American Black Duck,Mallard,Northern Pintail,...,White-winged Scoter,Surf Scoter,Black Scoter,Scoters,Bufflehead,Common Goldeneye,Long-tailed Duck,Mute Swan,Tundra Swan,American Coot
Unit,,,,,,,,,,,,,,,,,,,,,
1.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
2.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
3.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
4.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
5.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
6.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
7.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
8.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
9.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
10.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44
11.0,44,44,8,44,44,44,44,44,44,44,...,44,44,44,44,44,44,44,44,44,44

### Done Part 1
We already knew we had 11 observations for each year. Now we see that each unit number, 1-11, has 44 records. That is one for each year!

So it is save to say that every year has a single observation for each of the 11 Units. I think we now have data we can safely compare year after year, do you agree?

Note: In the cell above, you'll see the far left column, the index column, has a label of 'Unit.' That is because we grouped by Unit! If you scroll further up, you'll see when we grouped by 'Year' that the index has a label of 'Year.'

#### Continue on to the second notebook!